import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./provider";
import {Header} from "./components/Header"; // Ensure the path to Header component is correct

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Soundscape",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header /> {/* Add the Header component here */}
          {children}
        </Providers>
      </body>
    </html>
  );
}
